name: flight-planner
services:
  flight-planner-db:
    container_name: flight-planner-db
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flight-planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - flight_planner_db_data:/var/lib/postgresql/data

volumes:
  flight_planner_db_data: